### ISSUE TITLE
Factory Method design pattern is an Abstract Factory

### ISSUE THREAD

**Issue by hyankov** [Lc5/DesignPatternsCSharp#1]
Hi,

The provided example as 'factory method' is actually an 'abstract factory' implementation. There is virtually no difference between the two pattern examples in this repo.

**Comment by Lc5** [comment]
Hi! Thanks for your remark. Let me analyze it and I will get back to you.

**Comment by hyankov** [comment]
Hi,

Right now the only difference between the two is that the Abstract Factory returns a family of objects (i.e. has multiple factory methods), while the Factory Method has a single object creation method.

I think the idea behind the Factory Method is that the object which contains it can be derived and the method can be overridden to return a different object.

Wouldn't a better example be:

```
    public class AudiA8Factory : AudiFactory
    {
        public override ICar BuildCar()
        {
            return new AudiA8();
        }
    }
```
i.e. a more concrete implementation overrides the method.

**Comment by Lc5** [comment]
Hi - sorry for late reply. I think, that the main idea in Factory Method pattern - delegate creation of concrete objects to subclasses - can be achieved either by implementing specific interface or overriding the method in the parent class. I chose interface approach as it was simpler to me, although your example may be more in line what GOF describes. Thanks for you feedback! 

Yeah - I agree, there are a lot of examples out there, that confuses so called Factory and original Factory Method pattern. Good to be aware of differences.
